alert-message: "&c&lX-Ray&r &7%player% found &6%count% %item% at (%blockX%, %blockY%, %blockZ%)."
alert-log: "%player% found %count% %item% at (%blockX%, %blockY%, %blockZ%)."

mode: "BLOCK" # Options: "BLOCK", "VEIN".

# Log X-ray alert notifications.
log: true

monitored-blocks:
  - ANCIENT_DEBRIS
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_GOLD_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - GOLD_ORE
